add -Wno-unused-function flag
Since gcc-4.9, -wall option includes -W-unused-function by default. When
we compiled this package with latest toolchain, we saw below error:
I know the best way to resolve this issue is remove the function. But, I
don't decide whether the function is required or not.

[  134s] ../../../platform-abstractions/slp/resource-loader/resource-text-requester.cpp:55:6:
error: 'void Dali::SlpPlatform::{anonymous}::RemoveCharacter(Dali::Integration::TextResourceType::CharacterList&, uint32_t)' defined but not used [-Werror=unused-function]
[  134s]  void RemoveCharacter( TextResourceType::CharacterList& text, uint32_t code)

Change-Id: I9508616e5ef1dc520646cf147b65074eadbadb8c
Signed-off-by: Chanho Park <chanho61.park@samsung.com>